### ISSUE TITLE
location of config file

### ISSUE THREAD

**Issue by kairuku** [dfaust/plasma-applet-popup-launcher#1]
Hi, I was wondering if there is a file I can edit by hand to update my application entries without using the GUI, or to simply copy and paste my entries from a Popup Launcher on one panel to a new Popup Launcher on a different panel, e.g., to transfer all my entries from a side panel to a top panel without having to go add each entry one by one via the GUI.

Thank you for any insight :)

**Comment by dfaust** [comment]
All plasmoid settings are saved to `~/.config/plasma-org.kde.plasma.desktop-appletsrc`.
Search for `plugin=org.kde.popupLauncher` and you will find the settings in the form of:

```ini
[Containments][1][Applets][63]
immutability=1
plugin=org.kde.popupLauncher

[Containments][1][Applets][63][Configuration][ConfigDialog]
DialogHeight=540
DialogWidth=720

[Containments][1][Applets][63][Configuration][General]
apps=Awesomenauts.desktop,steam.desktop
icon=applications-games
title=Spiele
widgetWidth=180
```
