### ISSUE TITLE
Adhere to the iconographic configuration of the system.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [dfaust/plasma-applet-popup-launcher#14]
![image](https://user-images.githubusercontent.com/42837531/174347333-a76aadb0-fc3f-4e9c-bf6f-6980188d2b0e.png)
(All have been configured to be 16 pixels.)
![image](https://user-images.githubusercontent.com/42837531/174349219-549d0dab-067d-4d0c-b503-7277833ea4b9.png)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Wrong repository: https://github.com/Risu/CoolPopupQuicklaunch/issues/2

**Comment by dfaust** [comment]
Hey @BEEDELLROKEJULIANLOCKHART, looks like you opened all your issues for the wrong repo. No worries. But I'll close them here.

**Comment by RokeJulianLockhart** [comment]
@dfaust, that is very kind, but I actually did not; I believe that [I created solely one that was incorrect](http://github.com/dfaust/plasma-applet-popup-launcher/issues/12), whereas the rest were for this. It was merely coincidental that both repositories exhibited identical problems. Consequently, please reopen the ones that I did not close.

**Comment by RokeJulianLockhart** [comment]
@dfaust? https://github.com/dfaust/plasma-applet-popup-launcher/issues/14#issuecomment-1159818562
