### ISSUE TITLE
When start an app the applet request an xfce4-panel in execution

### ISSUE THREAD

**Issue by Fabick75** [dfaust/plasma-applet-popup-launcher#9]
Hi,
under mi Slackware 64  (current branch), I've updated KDE Plasma to the v.5.16 version, with Qt5 v.5.13.
Now, when try to launch any app configured on the applet, the respond with an error message that say "Impossible to add plugin to the panel: not found any instance of xfce4-panel in execution" .
I've installed xfce4-panel v.4.12, but don't have any other message to debug the launcher.

Any suggestion?

**Comment by dfaust** [comment]
What version of KDE Frameworks 5 do you have installed? And do you know if it was updated with that plasma update.
This bug seems different, but I have to wonder if it is somehow caused by the changes in KF5 version 5.61.0 (see #8). If you have KF5 5.61 installed, I would have expected you to hit that bug.

**Comment by Fabick75** [comment]
> What version of KDE Frameworks 5 do you have installed? And do you know if it was updated with that plasma update.
> This bug seems different, but I have to wonder if it is somehow caused by the changes in KF5 version 5.61.0 (see #8). If you have KF5 5.61 installed, I would have expected you to hit that bug.

Yes, I think that the version is 5.61 . There is any solution?

**Comment by dfaust** [comment]
> There is any solution?

Unfortunately not.

The KDE bug is tracked at https://bugs.kde.org/show_bug.cgi?id=411178.

**Comment by dfaust** [comment]
@Fabick75 could you try it again with version 1.3 (which I just released)? It uses a different way to launch applications.

**Comment by Fabick75** [comment]
I've tested on my system and now works flawless !

**Comment by dfaust** [comment]
great!
